### PR TITLE
fix compatibility to SVG.js 2.0

### PR DESCRIPTION
**Pull request by dhardtke**
as the title says this fixes the compatibility to SVG.js 2.x

Apparently, SVG.js 2.0 has changed the SVG.T**S**pan class to SVG.T**s**pan

### CODE REVIEW

**Comment by EpocDotFr** [comment]
+1

**Comment by Fuzzyma** [comment]
As far as I know you need no export module in svg.js v2 anymore because its already included. See here: https://github.com/wout/svg.js#import--export-svg

**Comment by dhardtke** [comment]
That is correct ;)

**Comment by EpocDotFr** [comment]
On the svg.js website there's no documentation about the advanced features of the export feature like this plugin

**Pull request closed without merging**
